version: '3'

services:
  master:
    build:
      context: './src/'
      dockerfile: 'Dockerfile.master'
    image: joy-master:latest
    ports:
      - '8081:8081'
    depends_on:
      - ml
    environment:
      - ML_HOST=ml

  ml:
    build:
      context: './src/'
      dockerfile: 'Dockerfile.ai'
    image: joy-ml:latest
    ports:
      - '8082:8082'
